config/routes.rb
Rails.application.routes.draw do
  
  get 'map/index'

  resources :locations do 
    resources :photos
  end
  
  devise_for :users
  root :to => 'pages#home'
  get 'about' => 'pages#about'
  get 'map' => 'map#index'
  get 'map2' => 'pages#map2'

  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :location
	belongs_to :user
	has_attached_file :image, styles: { large: "1100x880>", medium: "200x200>" }
	# has_attached_file :image,
 #    :path => ":rails_root/public/images/:id/:filename",
 #    :url  => "/images/:id/:filename"

	# do_not_validate_attachment_file_type :image
	validates_attachment :image, presence: true,
												content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
												size: { less_than: 5.megabytes }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except:  [:index, :show]
  
  # GET /photos
  # GET /photos.json
  # def index
  #   # @photos = Photo.all

  #   @location = Location.find(params[:location_id])
  #   @photos = @location.photos
  # end

  # GET /photos/1
  # GET /photos/1.json
  # def show
  #   @photo = Photo.find(params[:id])
  # end

  # GET /photos/new
  def new
    @location = Location.find(params[:location_id])
    @photo = @location.photos.new

    # @photo = Photo.new
  end

  # GET /photos/1/edit
  # def edit
  #   @photo = Photo.find(params[:id])
  # end

  # POST /photos
  # POST /photos.json
  def create
    # @photo = Photo.new(photo_params)
    @location = Location.find(params[:location_id])
    @photo = @location.photos.new
    # @photo = @location.photos.new(params.require(:photo).permit(:images))
    # @photo = @location.photos.create(photo_params.merge(user_id: current_user.id))
    # @photo.user_id = current_user.id
    # binding.pry
    # @photo.save
    if params[:images]
      params[:images].inject(true) do |memo, image|
        memo && @location.photos.create(image: image, user_id: current_user.id)
      end
      redirect_to location_path(@location)
    else
      flash.now[:success] = "Please choose one or more images"
      render :new
      # when rendering :new, must redefine @location and @photo
    end

    # if success
    #   redirect_to location_path(@location)
    # else
    #   render :new
    # end
    # if @photo.save
    #   if params[:images]
    #     params[:images].each { |image| 
    #       @location.photos.create(image: image, user_id: current_user.id) }
    #   end

    #   redirect_to session[:my_previous_url]
    # else
    #   render :new
    # end
    # respond_to do |format|
    #   if @photo.save
    #     format.html { redirect_to session[:my_previous_url], notice: 'Photo was successfully created.' }
    #     # format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
    #     format.json { render :show, status: :created, location: @photo }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @photo.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  # def update

  #   @location = Location.find(params[:location_id])

  #   @photo = @location.photos.find(params[:id])

  #   respond_to do |format|
  #     if @photo.update(photo_params)
  #       format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @photo }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @photo.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @location = Location.find(params[:location_id])
    @photo = @location.photos.find(params[:id])

    @photo.destroy
    respond_to do |format|
      format.html { redirect_to location_path(@location) }#, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      # params[:photo]
      params.require(:photo).permit(:images)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= simple_form_for [@location, @photo], html: { multipart: true } do |f| %>
  <%= f.error_notification %>

  <%= f.label :photos %>
  <%= file_field_tag "images[]", type: :file, multiple: true %>
  <br>
  <div class="form-actions">
  	<%= f.button :submit, class: "btn btn-primary btn-md" %>
  </div>
<% end %>










<%#= simple_form_for(@photo) do |f| %>
  <%#= f.error_notification %>

  <!-- <div class="form-inputs"> -->
  <!-- </div> -->

  <!-- <div class="form-actions"> -->
    <%#= f.button :submit %>
  <!-- </div> -->
<%# end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', location_photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Photos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_location_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_location_photo_path %>

app/views/photos/new.html.erb
<div class="container">
	<div class="row center">
		<div class="col-md-5 col-md-offset-3">
			<h1>Add New Photo(s)</h1>

			<%= render 'form' %>

			<%= link_to 'Back', locations_path %>
		</div>
	</div>
</div>









<!-- <h1>New Photo</h1> -->

<%#= render 'form' %>

<%#= link_to 'Back', location_photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_location_photo_path(@photo) %> |
<%= link_to 'Back', location_photos_path %>