config/routes.rb
Rails.application.routes.draw do
  
  get 'map/index'

  resources :locations do 
    resources :photos
  end
  
  devise_for :users
  root :to => 'pages#home'
  get 'about' => 'pages#about'
  get 'map' => 'map#index'
  get 'map2' => 'pages#map2'

  

end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
  	@locations = Location.order(:name)

    @geojson = Array.new

    @locations.each do |location|
      @geojson << {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [location.longitude, location.latitude]
        },
        properties: {
          name: location.name,
          equipment: location.equipment,
          # :'marker-color' => '#00607d',
          # :'marker-symbol' => 'circle',
          # :'marker-size' => 'medium'
        }
      }
    end

    respond_to do |format|
      format.html
      format.json { render json: @geojson }
    end
  end
end

app/helpers/map_helper.rb
module MapHelper
end

app/views/map/index.html.erb
<% provide(:title, "Map") %>
<body class="map">
	<div id="wrapper">
		<div id="sidebar-wrapper">
			<ul class="sidebar-nav">
				<% i = 0 %>
			  <% @locations.each do |location| %>
			  	<li id="<%= i %>"><a href="#" onclick="myClick(<%= i %>);"><%= location.name %></a></li>
			  	<% i += 1 %>
					<!-- <table>
						<tr>
							<td><%#= link_to 'Edit', edit_location_path(location) %></td>
							<td><%#= link_to 'Delete', location_path(location),
	              method: :delete,
	              data: { confirm: 'Are you sure?' } %></td>
						</tr>
					</table> -->
				<% end %>
			</ul>
		</div>

		<div id="page-content-wrapper">
			<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAnuqUbGzR772gmH_smmmsTPkZrCvFTrGg" type="text/javascript"></script>

			<%= javascript_include_tag 'create_markers' %>

			<%= link_to 'Add Location', new_location_path, class: "btn btn-primary btn-md" %>
			<%= link_to 'Edit Your Locations', locations_path, class: "btn btn-primary btn-md" %>
			<p></p>

			<div id="gmap" style="height:800px"></div>

			
		</div>
	</div>
</body>

<!-- <li id="0"><a href="#" onclick="myClick(0);">Mueller Park</a></li> -->