config/routes.rb
Rails.application.routes.draw do
  
  get 'map/index'

  resources :locations do 
    resources :photos
  end
  
  devise_for :users
  root :to => 'pages#home'
  get 'about' => 'pages#about'
  get 'map' => 'map#index'
  get 'map2' => 'pages#map2'

  

end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :user
	has_many :photos, :dependent => :destroy

	validates :name,
						presence: true,
						length: { minimum: 3, maximum: 50 },
						uniqueness: true

	validates :latitude,
						presence: true,
						numericality: true,
						length: { minimum: 7}

	validates :longitude,
						presence: true,
						numericality: true,
						length: { minimum: 8}

	validates :equipment,
						presence: true,
						length: { minimum: 5, maximum: 500 }
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # before_action :set_location, only: [:show, :edit, :update, :destroy] #remove repetition
  after_filter 'save_my_previous_url', only: [:new, :edit]
  before_filter :authenticate_user!, except:  [:index, :show] #devise method to require login for new

  def save_my_previous_url
    session[:my_previous_url] = URI(request.referer || '').path
  end

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.order(:name)
  end
  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])
    @photos = @location.photos
  end

  # GET /locations/new
  def new
    # @location = Location.new
    @location = current_user.locations.new #passes in user_id attribute / creates location under current user
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
    # @location = current_user.locations.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    # @location = Location.new(location_params)
    @location = current_user.locations.create(location_params)

    respond_to do |format|
      if @location.save

        if params[:images]
          # The magic is here ;)
          params[:images].each { |image|
            @location.photos.create(image: image, user_id: current_user.id)
          }
        end

        # format.html { redirect_to locations_path, notice: 'Location was successfully created.' }
        # format.html { redirect_to session[:my_previous_url], notice: 'Location was successfully created.' }
        format.html { redirect_to session[:my_previous_url] }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    @location = Location.find(params[:id])
    # @location = current_user.locations.find(params[:id])


    respond_to do |format|
      if @location.update(location_params)
        if params[:images]
          # The magic is here ;)
          params[:images].each { |image|
            @location.photos.create(image: image, user_id: current_user.id)
          }
        end

        # format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.html { redirect_to session[:my_previous_url] }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    # @location = Location.find(params[:id])
    @location = current_user.locations.find(params[:id])
    
    @location.destroy
    
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit( :name,
                                        :photos,
                                        :longitude,
                                        :latitude,
                                        :equipment)
    end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= simple_form_for @location, html: { multipart: true } do |f| %>
  <%= f.error_notification %>

  <%# if current_user == @location.user %>
    <%= f.input :name %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
    <%= f.input :equipment %>
  <%# end %>

  <%= f.label :photos %>
  <%= file_field_tag "images[]", type: :file, multiple: true %>
  <br>
  <div class="form-actions">
  	<%= f.button :submit, class: "btn btn-primary btn-md" %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<div class="container">
	<div class="row center">
		<div class="col-md-5 col-md-offset-3">
			<h1>Editing Location</h1>

				<%= render 'form' %>

				<%= link_to 'Show', @location %> |
				<%= link_to 'Back', locations_path %>
		</div>
	</div>
</div>

app/views/locations/index.html.erb
<% provide(:title, "Gallery") %>
<!-- <p id="notice"><%= notice %></p> -->
<body class="gallery">

<!-- <h1>Locations</h1> -->
<div class="button">
  <%= link_to 'Add Location', new_location_path, class: "btn btn-primary btn-md" %>
</div>
<p></p>

<div class="gallerybox">
  <ul class="grid">
    <% @locations.each do |location| %>
      <li>
        <div class="box">
          <% if location.photos.first %>
            <%= link_to image_tag(location.photos.first.image(:medium)), location_path(location) %>
          <% else %>
            <%= link_to 'Insert Your Photos', new_location_photo_path(location) %>
          <% end %>

          <p style="text-align: center;">
            <strong><%= location.name %></strong><br>
            <% if current_user == location.user %>
              <%= link_to 'Edit', edit_location_path(location), class: "btn btn-primary btn-xs" %>
              <%= link_to 'Delete', location, method: :delete, data: { confirm: 'Are you sure?' },
                                                                class: "btn btn-danger btn-xs" %>
            <% end %>
          </p>
        </div>
      </li>
    <% end %>
  </ul>
</div>

<!--
<script>
  $(window).load(function() {
    $('.grid').each(function() {
      $(this).gridEm( { minMargin: 25 } );
    });
  });

  $(window).resize(function() {
    $('.grid').each(function() {
      $(this).gridEm( { minMargin: 25 } );
    });
  });
</script>
-->

</body>

app/views/locations/new.html.erb
<div class="container">
	<div class="row center">
		<div class="col-md-5 col-md-offset-3">
			<h1>New Location</h1>

			<%= render 'form' %>

			<%= link_to 'Back', locations_path %>
		</div>
	</div>
</div>

app/views/locations/show.html.erb
<% provide(:title, "Gallery") %>
<p id="notice"><%= notice %></p>

<body class="show_page"></body>

<p class="location_title">
  <!-- <strong>Name:</strong> -->
  <%= @location.name %>
</p>

<div class="button">
  <%= link_to 'Add Photo', new_location_photo_path(@location), class: "btn btn-primary btn-md" %>
</div>
<p></p>

<div class="gallerybox">
  <ul class="grid">
    <%# unless @photos.empty? %>
      <% @photos.each do |pic| %>
        <li>
          <div class="box">
            <%= link_to image_tag(pic.image(:medium)), pic.image.url %>
            <div class="caption">
              <% if current_user == pic.user %>
                <%#= link_to "Edit", edit_location_photo_path(@location, pic) %>
                <%= link_to "", location_photo_path(@location, pic), :method => :delete,
                    :data => { :confirm => "Are you sure?" },  class: "glyphicon glyphicon-remove" %>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>
    <%# end %>
  </ul>
</div>

<%= link_to '', locations_path, class: "glyphicon glyphicon-bigger glyphicon-arrow-left" %>

<script>
  $(window).load(function() {
    $('.grid').each(function() {
      $(this).gridEm( { minMargin: 25} );
    });
  });

  $(window).resize(function() {
    $('.grid').each(function() {
      $(this).gridEm( { minMargin: 25} );
    });
  });
</script>