config/routes.rb
Rails.application.routes.draw do
  
  get 'map/index'

  resources :locations do 
    resources :photos
  end
  
  devise_for :users
  root :to => 'pages#home'
  get 'about' => 'pages#about'
  get 'map' => 'map#index'
  get 'map2' => 'pages#map2'

  

end

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
	<% if message_type == 'notice' %>
		<div class="alert alert-info"><span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span> <%= message %></div>
	<% else %>
		<div class="alert alert-warning"><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> <%= message %></div>
	<% end %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid-header">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- a class="navbar-brand" href="#">AustinParcourses</a> -->
      <%= link_to "Austin Fitness Trails", root_path, id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "About",   about_path %></li>
        <li><%= link_to "Map",   map_path, data: { no_turbolink: true} %></li>
        <!-- <li><%#= link_to "Map2",   map2_path, data: { no_turbolink: true} %></li> -->
        <li><%= link_to "Gallery",   locations_path, data: { no_turbolink: true} %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 
	  																					'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/shim' %>

	  
	</head>
	
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
      <%= render 'layouts/flash_message' %>
    </div>
		<%= yield %>

	</body>
</html>